FROM python:3.12-slim
WORKDIR /app
ENV PIP_NO_CACHE_DIR=1 PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

# Install CUDA-enabled PyTorch for GPU support
RUN pip install --no-cache-dir torch==2.8.0

COPY requirements.base.txt requirements.worker.txt ./
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY ./app ./app
COPY ./worker ./app/worker

ENV HF_HOME=/app/.cache/huggingface
CMD ["celery", "-A", "app.worker.celery_app", "worker", "-Q", "infer,ingress", "--concurrency=4"]